#!/bin/bash

source $HOME/.color
source $HOME/scripts/git-completion.bash
export HISTFILESIZE=50000
export PATH=$HOME/bin:$HOME/scripts:/usr/bin:$M2:/usr/local/bin:/usr/local/mysql/bin:$PATH:/usr/sbin:/usr/afsws/bin:/usr/afsws/etc
export PATH=/usr/local/bin:/opt/local/bin:/opt/local/sbin:$DERBY_INSTALL/bin:$HOME/Software/shell-scripts/dvcs:$PATH

function gchk() {
    git checkout `git branch -a | sed -e 's/\(.*\/\)//g' | grep $1 | head -n 1`
}

function gbr() {
    git branch -a | sed -e 's/\(.*\/\)//g' | grep $1
}

function gcma() {
    git commit -am "$1"
}

function gp() {
    git push
}

function gs() {
    git status
}

function gd() {
    git diff
}

export EDITOR="emacs -nw"
export PAGER=less
export CVS_RSH=ssh
export PS1="\t/\u/\H\w> "

export PYTHONPATH=$PYTHONPATH:$HOME/RedHawk

export MAVEN3_HOME=/opt/local/share/java/maven3
export M3=$MAVEN3_HOME/bin
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
export MAVEN_OPTS='-Xmx1024m'
export DERBY_INSTALL=~/Tools/db-derby-10.9.1.0-bin
export CLASSPATH=$CLASSPATH:~/Library/Java/bsh.jar:$DERBY_INSTALL/lib/derby.jar:$DERBY_INSTALL/lib/derbytools.jar:$WORKSPACE/database/drivers
export ANT_OPTS="-Xmx512m -XX:MaxPermSize=256m"

alias e="emacs -nw"

#Node
export NODE_PATH=/Volumes/home/:$HOME/workspace



alias e="emacs -nw"
alias ec="emacsclient -t"

function gpersonal() {
    #Git
    git config user.name "Seth Lakowske"
    git config user.email lakowske@gmail.com
}

#include work configuration if it exists
WORKBASHRC=$HOME/workScripts/workBashrc.sh
if [ -e $WORKBASHRC ]; then
    source $WORKBASHRC
fi

