#!/bin/bash

./install targetFile

CASK=$HOME/.cask/bin/cask

if [ ! -e $CASK ]; then
    echo "cask does not exist, so installing"
    curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
fi

cd $HOME/.emacs.d/

cask install

